** 关键字

http://baike.baidu.com/view/1849120.htm

abstract assert boolean break byte case catch char class const continue	
default	do double else enum extends final finally float for goto if
implements import instanceof int interface long	native new package private
protected public return short static strictfp super switch synchronized 
this throw throws transient try void volatile while

*** 语法结构

break case cathe const continue default do else fianl finally for goto 
if return switch throw try while

分支：switch case break default
判断：if else
异常：try catche finally throw
循环：do while for
定义：const fianl 
其它：goto return

final关键字可以用来修饰类、方法和变量（包括成员变量和局部变量）。

每个try块都必须至少有一个catch或finally子句。如果执行try块的任何部分，不论是否出现异常，也不论try或catch块是否包含return、continue或break语句，都一定会执行finally块中的代码。

*** 基本类型

boolean byte char double float int long short 
void false true null

byte char:8位
short:16位
int:32位
long:64位

*** 面向对象

abstract class enum extends implements import interface new package 
private protected public static super this throws

abstract关键字可以修改类或方法。
?implements继承多接口，只返回类别不同的方法怎么处理。
private protected public:类、方法或字段
static:可以应用于内部类（在另一个类中定义的类）、方法或字段（类的成员变量）。
*** 其它

assert instanceof native synchronized transient volatile strictfp
strictfp 关键字可应用于类、接口或方法。

** 基础类

*** 包装类
Boolean:包装对象类。
Byte：定义代表此类型的值的范围的MIN_VALUE和MAX_VALUE常量。
Character：包含一些可用来处理char变量的static方法，这些方法包括isDigit()、isLetter()、isWhitespace()和toUpperCase()。
Double：包装对象类用来定义常量MIN_VALUE、MAX_VALUE、NEGATIVE_INFINITY、POSITIVE_INFINITY和NaN。
Float包装对象类用来定义常量MIN_VALUE、MAX_VALUE、NEGATIVE_INFINITY、POSITIVE_INFINITY和NaN。
Integer类是int原始类型的包装对象类。它定义代表此类型的值的范围的MIN_VALUE和MAX_VALUE常量。
Long类是long原始类型的包装对象类。它定义代表此类型的值的范围的MIN_VALUE和MAX_VALUE常量。
Short类是short原始类型的包装对象类。它定义代表此类型的值的范围的MIN_VALUE和MAX_VALUE常量。

*** 日期

*** 文本


** 集合

** GC

** JVM

   
